name: Build and deploy ASP.Net Core Package 

env:
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Lista arquivos
        run: ls -l

      - name: Restore
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --no-restore

      - name: dotnet release
        run: dotnet build -c Release

      - name: Generate Package
        run: dotnet pack -c release -o ./dist/

  deploy:    
    runs-on: ubuntu-latest
    needs: build    

    steps:
      - name: Publish Package        
        run: dotnet nuget push ./dist/* --api-key ${{secrets.API_KEY_PACKAGE}} --source https://nuget.pkg.github.com/raphaac/index.json             
